### ISSUE TITLE
Undefined class constant 'HTTP_REDIRECTED_URL' error

### ISSUE THREAD

**Issue by bpot** [census-instrumentation/opencensus-php#111]
If the request returns a redirect status code then `RequestHandler.php` tries to add a `HTTP_REDIRECTED_URL` attribute to the span but fails because `HTTP_REDIRECTED_URL` is only defined in `StackdriverExporter.php`.

I'm not sure what the correct fix is here. We could define the value in `RequestHandler.php` but it seems like this is functionality that should live in the stack driver exporter.

**Comment by chingor13** [comment]
Yes, this belongs in the StackdriverExporter. There is a PR for the specs that lays out suggested common attribute names, but the redirected url is not included.
