### ISSUE TITLE
Allow Tracer usage in code which may or may not have an active tracer

### ISSUE THREAD

**Issue by bpot** [census-instrumentation/opencensus-php#116]
The span methods on `OpenCensus\Trace\Tracer` assume that a trace has already been started and will throw an error (e.g. `Call to a member function tracer() on null`) if they are called without an active trace instance.

We got bit by this because we have multiple entry points in our codebase some of which started a trace and some of which didn't. It seems like it would be useful to either make all of the calls on `Tracer` no-ops if there isn't an instance or provide a `Tracer::active()` method which can be used as a guard around calls to the other `Tracer` methods.

I'm happy to send a PR for whichever path is seems best.

**Comment by chingor13** [comment]
It's probably best to make the calls no-ops otherwise you'll be littering your code with the extra check.
