### ISSUE TITLE
FileExporter report fail to serialize spans

### ISSUE THREAD

**Issue by arquivei** [census-instrumentation/opencensus-php#119]
As `OpenCensus\Trace\Span` does not implements `JsonSerializable`, calling `json_encode` on `$tracer->spans()` will produce empty JSON objects.

I see two options here:
1. convert `OpenCensus\Trace\Span` into `Google\Cloud\Trace\Span` following `StackdriverExporter` approach;
2. or force `OpenCensus\Trace\Span` implement `JsonSerializable`

For testing propose I already implemented the first option [here](https://github.com/arquivei/opencensus-php.git).

Any thoughts on this issue?

Thanks!

**Comment by chingor13** [comment]
I wouldn't do option 1 because it forces `FileExporter` to have a dependency on the `google/cloud-trace` package (which is not needed unless you're using the `StackdriverExporter`). 

Instead, we could do a conversion to serializable arrays within the `FileExporter`.

**Comment by lemuelroberto** [comment]
Agreed ;) I'll submit a pull request.

**Comment by arquivei** [comment]
Agreed ;) I'll submit a pull request.

**Comment by chingor13** [comment]
Fixed in #124
