### ISSUE TITLE
Async data export

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#123]
Most exporters currently execute at the end of the request while blocking the end of the request. The `StackdriverExporter` can use an experimental mechanism provided by the `google/cloud-core` package that uses shared memory for offloading the API call to a separate process.

We can create an `AsyncExporter` (for any async method) that accepts any other `ExporterInterface` and reports using that exporter asynchronously. This should make it so that each exporter doesn't have to manage async itself.

**Comment by jcchavezs** [comment]
> Most exporters currently execute at the end of the request while blocking the end of the request.

By this you mean something like `register_shutdown_function`?

**Comment by chingor13** [comment]
Yes, we use `register_shutdown_function` now to signal the end of the request so we export the spans for the current request. At this point, the exporter will synchronously export that data - which could be slow and can affect the latency of the request. The optimization the `google/cloud` library does is to save the data to export to shared kernel memory (very fast) and a separate script running as a daemon does the export to the external service.

**Comment by jcchavezs** [comment]
Interesting @chingor13. I did not know about the `google/cloud` optimizations. Where can I find a link for it?

**Comment by jcchavezs** [comment]
@chingor13 is `APCu` an option?

**Comment by chingor13** [comment]
For any of our libraries, we try and hit the least common denominator for PHP installs. Most PHP installations *should* have APCu available as an extension, but not all do -- so we probably don't want a solution that totally depends on that extension. That being said, the [google/cloud](https://github.com/GoogleCloudPlatform/google-cloud-php/tree/master/src/Core/Batch) solution does utilize sem/sysv extensions that ship as part of PHP for most installations.

As for APCu itself, I don't think we can use it as it's for caching and not for use as a queue (unless I'm misunderstanding the use case here).

We could consider integrating a library that abstracts the queuing mechanism that could provide implementations depending on the extensions available.

**Comment by jcchavezs** [comment]
Agree. I believe abstracting the queue mechanism is a good idea.

The google cloud solution seems to be the best fit tho.

As for the APCu, you can basically drop traces into APCu and use a counter (again in APCu) and then based on the bytesize do the bulk reporting to the backend.

**Comment by basvanbeek** [comment]
This can be solved with the approach we've taken for adding stats. PR #220 includes a PHP userland exporter (DaemonClient) that immediately sends stats (and potentially traces) over a non blocking unix socket with a configurable max send duration. An accompanying Daemon service written in Go ingests the data and moves it to OpenCensus Agent for further handling / export. This allows keeping the processing time in PHP to a minimum and does not allow stalls due to congestion or slow network links. Added bonus is having all backends and features supported from the OC Agent / OC Go implementations avoiding duplication of effort.

**Comment by basvanbeek** [comment]
DaemonClient has been merged into project. We now have a way to transport both stats and traces outside the PHP request path
