### ISSUE TITLE
Zipkin exporter observations

### ISSUE THREAD

**Issue by jcchavezs** [census-instrumentation/opencensus-php#125]
A couple of observations related to zipkin exporter:

1. Since the reporter only uses one endpoint from the backend, zipkin instrumentations usually don't store host/port and uri but the full endpoint url instead `endpointUrl="http://localhost:9411/api/v2/spans`.
2. In the [exported format](https://github.com/census-instrumentation/opencensus-php/blob/master/src/Trace/Exporter/ZipkinExporter.php#L173) there is no `kind` attribute ([link](https://zipkin.io/zipkin-api/#/default/post_spans)), is it possible it is being added as a tag and gets lost because of that?

If you consider these observations are valid I could help with them.

**Comment by chingor13** [comment]
For number 1, yes it looks like we can remove the host and port instance variables.
As for number 2, the opencensus data model does not include a field for span kind. Until a common attribute is defined, we can't really set that value.

**Comment by jcchavezs** [comment]
Nice @chingor13 I will open a PR for point 1.
For point 2 I will do some research.

**Comment by jcchavezs** [comment]
Related to the `span.kind` I found this (thanks to @adriancole): https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java#L169

**Comment by chingor13** [comment]
Closed via #138
