### ISSUE TITLE
Segfault when using extension for StackdriverExporter or Wordpress integration

### ISSUE THREAD

**Issue by bshaffer** [census-instrumentation/opencensus-php#129]
The following results in a `segfault: 11` on PHP 7.0, 7.1, and 7.2:

```
/** Set up tracing integration */
use OpenCensus\Trace\Tracer;
use OpenCensus\Trace\Exporter\StackdriverExporter;
use OpenCensus\Trace\Integrations\Wordpress;

Tracer::start(new StackdriverExporter());
Wordpress::load();
```
Commenting either `Tracer::start` or `Wordpress::load` results in the same error, but if only the `EchoExporter` is used, the segfault does not happen.

This works just fine if I disable the `opencensus.so` extension.

**Comment by bshaffer** [comment]
PHP version: PHP 7.2.1 
OS: macOS High Sierra 10.13.1

**Comment by chingor13** [comment]
I am able to reproduce this on OSX. It appears to be happening in `opencensus_trace_call_user_function_callback`

**Comment by bshaffer** [comment]
Can confirm this is only happening on OSX for me, I was able to get it working on Linux.

**Comment by bshaffer** [comment]
Confirmed this fixes it! Thanks!
