### ISSUE TITLE
Add multi-sampler implementation

### ISSUE THREAD

**Issue by tmatsuo** [census-instrumentation/opencensus-php#144]
It will receive a list of SamplerInterface then

- Use the sampler in the order
- Returns true when a sampler returns true
- Try the next one in the list when a sampler returns false
- When exhausting the list, return false

**Comment by chingor13** [comment]
> Returns true when a sampler returns true

I think we actually want the opposite - if a sampler says to skip this request, then skip it - no need to ask further samplers.
