### ISSUE TITLE
Status of Stats

### ISSUE THREAD

**Issue by andrewhowdencom** [census-instrumentation/opencensus-php#173]
Hola,

I couldn't see it otherwise, nor mention of a roadmap so I'm dumping this in an issue. I'm super excited about this project! However, I'm curious - how are stats going to be implemented? Additionally, is there some way I can help here? (I have limited time constraints, but would be keen to give it a go)

At one point I wrote up how I wanted express this in an application called "Magento" -- 
https://community.magento.com/t5/Magento-2-x-Feature-Requests-and/Create-a-mechanism-to-checkpoint-time-series-data-for-use-in-the/idi-p/76504

Cheers!

**Comment by chingor13** [comment]
Thanks for your interest! I don't believe anyone is actively working on the tags/stats implementations yet. 

The census-instrumentation organization has published [some specifications](https://github.com/census-instrumentation/opencensus-specs) and some [data models](https://github.com/census-instrumentation/opencensus-proto) to keep each language's implementations feeling the same.

My understanding for the stats implementation is limited, but the data aggregation stuff may be difficult as PHP cannot easily persist data between requests to do the aggregation.

**Comment by bogdandrutu** [comment]
@shahprit I think here is where you have to publish the plan to support this when is defined.

**Comment by basvanbeek** [comment]
A first iteration of Stats can be found in PR #220. 

We have chosen a sidecar design where all stats handling is offloaded to an external Daemon service communicating over a unix socket (Daemon is written in Go and included in the PR). This Daemon service can then forward to the OC Agent for export to the various OC supported backends.

**Comment by basvanbeek** [comment]
Initial version of Stats has been merged. Give it a try!
