### ISSUE TITLE
Reimplement span kind

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#18]
Stackdriver Trace and Zipkin both support the kind of span (client, server, or unknown)

**Comment by adriancole** [comment]
fyi due to overwhelming demand, zipkin supports messaging kinds, recently.
PRODUCER and CONSUMER http://zipkin.io/zipkin-api/#/default/post_spans

**Comment by chingor13** [comment]
I believe the v1 api also has a way to tag annotations for start and stop times with cs/cr (client send/receive) and ss/sr (server send/receive). The current `ZipkinReporter` just hard codes cs/cr because it seemed like a reasonable default.

When reimplementing this, the `ZipkinReporter` should respect the span kind and set cs/cr or ss/sr appropriately.

**Comment by chingor13** [comment]
@adriancole Is there a thread I can read about why PRODUCER/CONSUMER was requested beyond CLIENT/SERVER?

**Comment by adriancole** [comment]
>
> @adriancole <https://github.com/adriancole> Is there a thread I can read
> about why PRODUCER/CONSUMER was requested beyond CLIENT/SERVER?
>

Sure, some of it is covered in the release notes here:
https://github.com/openzipkin/zipkin/releases/tag/1.29.2

There are a number of very long issues associated with this, so let me know
if you want more links. or ping me here https://gitter.im/openzipkin/zipkin
