### ISSUE TITLE
PECL extension inclusion in production

### ISSUE THREAD

**Issue by iamacarpet** [census-instrumentation/opencensus-php#197]
Hello @chingor13 

I've asked some other engineers at Google about inclusion of your PECL extension in the PHP 7.2 runtime for Standard, but I wanted to drop you a line to ask you about it too.

It is still marked as Alpha, but then so is the whole OpenSensus library and they are asking us to use it for Trace support on that platform.

Do you think it'll be suitable for inclusion in the runtime and for running in production?
If not now, any time in the near future?

Regards,
iamacarpet

**Comment by chingor13** [comment]
Feature-wise, the extension has all the planned trace features with a single unresolved issue (#196). Stability-wise, we do have a full suite of unit and integration tests across different PHP versions and environments. The limiting factor for the Alpha/Beta/GA designation is the entire OpenCensus product (specs, etc) officially going 1.0 and users testing/feedback.

We do make the extension available for the PHP runtime for GAE Flexible Environment for PHP 7+. It seems reasonable to allow it in the Standard environment (hopefully opt-in enabling).
