### ISSUE TITLE
Working example cross platform tracing

### ISSUE THREAD

**Issue by dragoscirjan** [census-instrumentation/opencensus-php#204]
Hi, 

My team and I are looking more and more into implementing a distributed tracing solution; however, because we're working on an SPA solution, we need a cross-platform example on how distributed tracing would work or a minimal tutorial on how it could be implemented.

Could you guys give us a hint, or redirect us to a working example?

Many thanks in advance.

**Comment by mayurkale22** [comment]
@dragoscirjan We have just [published](https://github.com/GoogleCloudPlatform/microservices-demo) hipster opencensus demo on github (blog coming soon)

**Comment by dragoscirjan** [comment]
@mayurkale22 I've taken a fast look over the demo, however, I'm missing a major part in it. I mentioned SPA in my question (Single Page Application). This would mean having a Javascript Open Census API for browsers as well. Is there any plan for it?

**Comment by chingor13** [comment]
@dragoscirjan This repository is only for the PHP implementation. The javascript implementation is being worked on https://github.com/census-instrumentation/opencensus-node although I'm not sure what state it's in. You may also want to ask around for examples in the organization's gitter: https://gitter.im/census-instrumentation/Lobby

As for an example/tutorial, the folks working on the https://opencensus.io are working to build tutorials and guides for things like interop between services.

Closing as this is not the right place for this question.

**Comment by dragoscirjan** [comment]
@chingor13 `opencensus-node` is node only. Since it uses NodeJs native libraries it can't be used within browsers. So my search for examples and browser implementation remains. I posted here as well as in the official browser (appear to be) project: https://github.com/census-instrumentation/opencensus-js-core in the hope of finding someone who could help me :) I will address the Gitter community as well. Thank you.
