### ISSUE TITLE
Considered protected instead of private ? 

### ISSUE THREAD

**Issue by dragoscirjan** [census-instrumentation/opencensus-php#206]
Hi!

Would you consider making class properties `protected` instead of `private`? 

Considering #205 (I just discovered I need to extend Guzzle Middleware class as well) all properties are private which won't let me extend classes but rewrite pretty much everything.

**Comment by chingor13** [comment]
Can you elaborate on what you're trying to do? That class is not required to use and is pretty simple.

**Comment by jcchavezs** [comment]
@dragoscirjan I think you can perfectly do everything using inheritance by using composition. Anything particular you want to extend the classes?

**Comment by dragoscirjan** [comment]
@jcchavezs it seems I'm missing some knowledge. Could you elaborate how I could extend, let's say, Guzzle Middleware class to use a different propagator?
@chingor13 please #205 and you will better understand what I need to do
