### ISSUE TITLE
Implement APIs and Data Model

### ISSUE THREAD

**Issue by jparsana** [census-instrumentation/opencensus-php#207]
# APIs / Data Model across languages should match

There are two main components of the Stats APIs - tags and stats. The stats component provides the framework to define measures (e.g. rpc client latency) and record stats against those measures. The tags component provides a way to break down the data for a measure along user-defined dimensions. Finally, views, which are part of stats, all users to specify the aggregations of the stats that they are interested in. The language-independent specifications of tags and stats are available on [opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/), specifically:

[OpenCensus Tags](https://github.com/census-instrumentation/opencensus-specs/tree/master/tags)
[OpenCensus Stats](https://github.com/census-instrumentation/opencensus-specs/tree/master/stats)

**Comment by basvanbeek** [comment]
First version is awaiting review / discussion in #220

**Comment by basvanbeek** [comment]
#220 has been merged
