### ISSUE TITLE
Core Stats Library Implementation

### ISSUE THREAD

**Issue by jparsana** [census-instrumentation/opencensus-php#208]
An implementation of the core library provides an implementation of the OpenCensus Tags and Stats APIs that provides for the definition of OpenCensus tags, the definition of OpenCensus Measures, recording values against measure with a set of tags, and exporting the aggregated stats. Similar to the APIs, there is a language-independent specification of the implementation available on [opencensus-specs](https://github.com/census-instrumentation/opencensus-specs/), specifically:

[OpenCensus Tags](https://github.com/census-instrumentation/opencensus-specs/tree/master/tags)
[OpenCensus Stats](https://github.com/census-instrumentation/opencensus-specs/tree/master/stats)

**Comment by basvanbeek** [comment]
Note: since we're using a separate daemon application for the heavy lifting of stats, not all implementation will be handled in PHP but in Go. 
The Go daemon application will be part of this repo.

**Comment by basvanbeek** [comment]
Initial version is awaiting review / discussion in #220

**Comment by basvanbeek** [comment]
#220 has been merged so we have our initial Stats and Tags implementation available
