### ISSUE TITLE
Export to Stackdriver

### ISSUE THREAD

**Issue by jparsana** [census-instrumentation/opencensus-php#209]
1. Convert OpenCensus Stats/Metrics data model to Stackdriver data model.
2. Set correct domain name prefix for uploaded Stackdriver metrics.
3. Auto-detect and populate MonitoredResource and associate it with metrics (tracking issue [Ruby](https://github.com/census-instrumentation/opencensus-ruby/issues/66)).
4. Add one additional task label for metrics to avoid potential race condition on the same machine. See [what-is-opencensus_task-metric-label](https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#what-is-opencensus_task-metric-label-).
5. E2E tests to verify exporting to actual Stackdriver backend, especially when there are multiple exporters running simultaneously.

**Comment by basvanbeek** [comment]
Export to StackDriver is dependent on OC Agent. The PHP implementation proxies the stats API output straight to the Go Daemon service which in turn uses OpenCensus-Go and the OpenCensus Go Agent for further handling and export to backends including StackDriver.

**Comment by basvanbeek** [comment]
PR #220 has been merged. Stackdriver export can be enabled through a set-up with the Daemon and OpenCensus Agent.
