### ISSUE TITLE
Export to Prometheus

### ISSUE THREAD

**Issue by jparsana** [census-instrumentation/opencensus-php#211]
1. Convert OpenCensus Stats/Metrics data model to Prometheus data model (Gauge, Counter, Histogram).
2. E2E tests to verify the Prometheus exporter can export metrics to Prometheus server via HTTP.

**Comment by basvanbeek** [comment]
Export to Prometheus is dependent on OC Agent. The PHP implementation proxies the stats API output straight to the Go Daemon service which in turn uses OpenCensus-Go and the OpenCensus Go Agent for further handling and export to backends including Prometheus.

**Comment by basvanbeek** [comment]
Export to Prometheus is available through connection with Daemon and OpenCensus Agent.
