### ISSUE TITLE
opencensus.so: undefined symbol: ZVAL_DESTRUCTOR

### ISSUE THREAD

**Issue by chenryn** [census-instrumentation/opencensus-php#235]
I try to use opencensus in wordpress, but only get http attributes, not any mysql query. Then I installed the optional opencensus.so extensions, and restart the php73-fpm service. Got Error:

> [12-Apr-2019 13:03:52] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'opencensus' (tried: /opt/remi/php73/root/usr/lib64/php/modules/opencensus (/opt/remi/php73/root/usr/lib64/php/modules/opencensus: cannot open shared object file: No such file or directory), /opt/remi/php73/root/usr/lib64/php/modules/opencensus.so (/opt/remi/php73/root/usr/lib64/php/modules/opencensus.so: undefined symbol: ZVAL_DESTRUCTOR)) in Unknown on line 0

**Comment by chenryn** [comment]
I found the reason, need to change ZVAL_DESTRUCTOR  to zval_ptr_dtor.

**Comment by varunpalekar** [comment]
@chenryn Please guide me how to change ZVAL_DESTRUCTOR to zval_ptr_dtor if I install opencensus from pecl ?

**Comment by chenryn** [comment]
@varunpalekar I just download the tgz from pecl and modify it. BTW: this git repo has already changed the variable. We only need to rush a new pecl version.

**Comment by Kyle2142** [comment]
building from source (or pecl) still gives this error, because contrary to @chenryn's comment on Apr 23, the code has not changed or has reverted.
Please reopen this issue

**Comment by bobstrecansky** [comment]
We are also seeing this problem; I think this needs to be reopened as well.

**Comment by mcfedr** [comment]
@bobstrecansky I think its fixed on master, but not released.

**Comment by bobstrecansky** [comment]
I agree.  It appears that this hasn't been released in roughly 14 months; Is there another release planned soon?  cc:\ @chingor13, as he performed the last release.

**Comment by eteubert** [comment]
Ran into it as well, still not released on pecl? Does anyone have the details on the workaround?

**Comment by mcfedr** [comment]
> Ran into it as well, still not released on pecl? Does anyone have the details on the workaround?

Work around is to install from source using master branch.

**Comment by Kyle2142** [comment]
for anyone still finding this via web search and wants a quick solution:
follow 
[build from source](https://github.com/census-instrumentation/opencensus-php/blob/master/ext/README.md) up to step 3
```shell
find . -type f -exec sed -i 's/ZVAL_DESTRUCTOR/zval_ptr_dtor/g' '{}' \;
```
and then continue with step 4

btw the extension works on PHP7.4 other than failing the "integer as name" test

**Comment by kees-tce** [comment]
When will the new pecl version be pushed? This issue has been reported and acknowledged over a year ago?

**Comment by varunpalekar** [comment]
I am using pecl to install `opencensus` and not facing any issue.

Ref: https://github.com/varunpalekar/php-ci-cd/blob/develop/Dockerfile#L26

**Comment by ibnujakaria** [comment]
```
opencensus.so: undefined symbol: ZVAL_DESTRUCTOR
```

Im enabling on Google App Engine Flex Environment of PHP 7.3 and got this error.

**Comment by Nowaker** [comment]
The library in PECL is still broken. Here's my environment:
```dockerfile
FROM wordpress
RUN pecl install opencensus-alpha
COPY custom-php.ini "$PHP_INI_DIR/conf.d/custom.ini"
```

Code:
```php
<?php
use OpenCensus\Trace\Integrations\Wordpress;
Wordpress::load();
```

Error:
```
wordpress_1  | apache2: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/opencensus.so: undefined symbol: ZVAL_DESTRUCTOR
```

**Comment by Nowaker** [comment]
Also tried against `wordpress:php7.3`. Same problem.

It works against  `wordpress:php7.2`.

**Comment by MrMage** [comment]
The version on PECL seems to never get updated. Here's how to compile the latest version of the extension, compatible with PHP 7.1 to 8.0:

```bash
git clone --recursive --depth=1 https://github.com/census-instrumentation/opencensus-php.git \
  && cd opencensus-php/ext \
  && phpize \
  && CFLAGS="-O2" ./configure \
  && make -j $(nproc) \
  && sudo make install \
  && cd ../.. \
  && rm -rf opencensus-php
```

**Comment by Nowaker** [comment]
@MrMage Thank you! It works.

```dockerfile
RUN apt-get -yqq install git && \
    cd /tmp && \
    git clone --recursive --depth=1 https://github.com/census-instrumentation/opencensus-php.git && \
    cd opencensus-php/ext && \
    phpize && \
    CFLAGS="-O2" ./configure && \
    make -j $(nproc) && \
    make install && \
    cd ../.. && \
    rm -rf opencensus-php
```
