### ISSUE TITLE
PHP 7.3 compatibility

### ISSUE THREAD

**Issue by bschmitt** [census-instrumentation/opencensus-php#241]
Any new releases planned to make the library (including the pecl extension) PHP 7.3 compatible?

Currently running into the issue already fixed here, which is still not in the latest release:
https://github.com/census-instrumentation/opencensus-php/pull/195

**Comment by samcday** [comment]
FWIW we forked this (apparently dead?) project and applied the commit from #195 ourselves. We've been running that in production on PHP 7.3 for a couple of weeks with no issues.

**Comment by basvanbeek** [comment]
If you use the latest commit from master it will be PHP 7.3 compatible and it adds OpenCensus Metrics as well as the OC Daemon for PHP (taking the transport of traces and metrics outside of the request path).

**Comment by samcday** [comment]
@basvanbeek yeah I saw that, but felt like it was a pretty major unreleased change with no information about its stability or production readiness.

Have you (or others?) been using it in a production setting for a while? Is it ready for use? If it is, then why hasn't someone cut a new release for it yet? :)
