### ISSUE TITLE
Update dependencies to allow Ramsey/Uuid version 4

### ISSUE THREAD

**Issue by MarkBaker** [census-instrumentation/opencensus-php#256]
Is there any possibility of a new tagged release that allows ramsey/uuid 3 or 4, and not simply 3?
PHP, and your dependencies have moved on since the last tagged release.

**Comment by meshenka** [comment]
same issue here

**Comment by sdwru** [comment]
same here

**Comment by MAJA-Lin** [comment]
Same here.

**Comment by yotov** [comment]
Any news about this pull request? I can't run open census with the latest laravel/lumen due to this restriction
