### ISSUE TITLE
php7.4 compatible code release branch

### ISSUE THREAD

**Issue by kishoresai438** [census-instrumentation/opencensus-php#265]
Hi Team,

I saw that there is one commit to fix PHP7.4 compatible curly braces issue. Code is in `dev-master`(https://github.com/census-instrumentation/opencensus-php/pull/258/files), but not in any release branch. Can we expect this in release branch?

I am using Stack driver exporter lib, but they are not supporting `dev-master`. So please provide release branch for that. So that they can update stackdriver exporter lib. Thanks.
https://packagist.org/packages/opencensus/opencensus-exporter-stackdriver

**Comment by boris-hocde** [comment]
@kishoresai438 Don't wait too long. As quick dirty fix, you can temporary disable `E_DEPRECATED` reporting when starting the tracer:

```php
$initialErrorReporting = error_reporting();
error_reporting($initialErrorLevel ^ E_DEPRECATED);

Tracer::start($exporter, [
    'sampler' => $sampler,
]);

error_reporting($initialErrorReporting);
```
