### ISSUE TITLE
Please tag v0.6.0

### ISSUE THREAD

**Issue by bshaffer** [census-instrumentation/opencensus-php#268]
We need a new git tag for opencensus `v0.6.0` so that composer can pull down the latest changes for PHP 8.0 compatibility in master. This release will add the following things since the last tag:

- feat: OpenCensus Stats implementation (#220)
- fix: PHP 7.4 Compatibility Fix (#259)
- chore: improved opencensus-php dockerfile adding composer+git for easy usage (#225)
- chore: Update Readme (#222)

**Comment by bshaffer** [comment]
@ericnorris @chingor13

**Comment by ericnorris** [comment]
Hey @bshaffer! I, too, would like this to be tagged, and had reached out to Google via our TAM to try and make this happen. If I could release this I would, but I have nothing to do with this project apart from submitting a PR for PHP 7.4.

In fact, the last comment in that PR is me asking @chingor13 to tag a release :)

**Comment by bshaffer** [comment]
Please take a look @mayurkale22!

**Comment by bshaffer** [comment]
It's done! thank you!

[v0.6.0](https://github.com/census-instrumentation/opencensus-php/releases/tag/v0.6.0)
