### ISSUE TITLE
JIT is incompatible with OpenCensus Extension

### ISSUE THREAD

**Issue by kemurayama** [census-instrumentation/opencensus-php#285]
Hi, 

I used the opencensus extension with JIT compiler but the JIT compiler was disabled with the error. 

```
PHP Warning:  JIT is incompatible with third party extensions that override zend_execute_ex(). JIT disabled. in Unknown on line 0
```

The extension seems override the method `zend_execute_ex`.

https://github.com/census-instrumentation/opencensus-php/blob/dcc7feab38507dedc0097d5bb459b81b1439c1ae/ext/opencensus_trace.c#L38

Is OpenCensus Extension compatible with JIT compiler ? I would like to use the extension to trace the library I use in my application. 

Also appreciate any workaround for tracing third party libraries. Thanks.

**Comment by MrMage** [comment]
The extension predates the JIT compiler, and it doesn't really receive future development anymore. In addition, its overriding of `zend_execute_ex` does cost a bit of performance (~20%).

I used to use this extension in the past (even contributed fixes to it), but mostly leave it disabled these days to benefit from better default performance. Instead, I manually trace performance-critical sections using `Tracer::inSpan` in the PHP library (i.e. without the native extension); it should get you the insights you need, without the performance penalty.

**Comment by kemurayama** [comment]
@MrMage Thanks for sharing the performance information !! It is very useful for me when I instrument. 
Do you have any recommendation when we want to capture traces with third party libraries (such as DB) ? 
If I used `Tracer::inSpan`, I would want to trace more specifically to figure out if the latency comes from my implementation or not.

**Comment by MrMage** [comment]
I trace e.g. all Laravael controller route handlers and all DB queries automatically. From there, I know which routes are slow, and can add more instrumentation to those routes as needed.

Here's the code I use:

**`app/Http/Controllers/Controller.php`**

```php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use OpenCensus\Trace\Tracer;

class Controller extends BaseController
{
    use DispatchesJobs,
        ValidatesRequests,
        AuthorizesRequests;

    public function callAction($method, $parameters)
    {
        return Tracer::inSpan(
            [
                'name' => static::class . '::' . $method,
            ],
            fn () => parent::callAction($method, $parameters)
        );
    }
}
```

**`app/Database/PostgresConnection.php`**

```php
<?php

declare(strict_types=1);

namespace App\Database;

use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Database\Grammar;
use OpenCensus\Trace\Span;
use OpenCensus\Trace\Tracer;

class PostgresConnection extends \Illuminate\Database\PostgresConnection
{
    /* other methods */

    protected function run($query, $bindings, \Closure $callback)
    {
        // Trace any database queries. Alternatively, this could also be implemented by listening to
        // `\Illuminate\Database\Events\QueryExecuted` events; see e.g. `\Spatie\LaravelIgnition\Recorders\QueryRecorder`.
        $args = \func_get_args();
        return Tracer::inSpan(
            [
                'name' => 'DatabaseConnection::run',
                'attributes' => [
                    'query' => $query,
                ],
                'kind' => Span::KIND_CLIENT,
            ],
            // Can't use `\func_get_args()` directly here because the arguments to `fn ()` are empty.
            fn () => parent::run(...$args)
        );
    }
}
```

**Comment by kemurayama** [comment]
@MrMage Thanks. These samples are really helpful for me to understand how to instrument the code. 
And I really appreciate your kind response.
