### ISSUE TITLE
Make models match the shared data model

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#38]
https://github.com/census-instrumentation/opencensus-proto/blob/master/trace/trace.proto

The extension and PHP models returned should match these structures.

- [x] Labels -> Attributes
- [ ] Span kind -> sameProcessAsParent
- [ ] Span should have status

**Comment by bogdandrutu** [comment]
Also the API should match the same proto:
* Labels -> Attributes.
* No span kind (only has_parent_same_process).
* Use status to report the status of the Span instead a label.
