### ISSUE TITLE
Use Stackdriver Trace V2 API

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#73]

**Comment by chingor13** [comment]
For PHP, we'll need a the generated discovery doc for the V2 Stackdriver Trace API. The Gapic clients are gRPC only and we can't guarantee that gRPC is installable for all PHP hosting environments.

Currently, the V2 Trace API only has write endpoints (no read endpoints), however, it looks like read endpoints should exist.

**Comment by liyanhui1228** [comment]
Yes, it's weird that the V2 Trace API removes the read endpoints. In the Python system tests I'm using `get_trace` API for checking whether the spans have been sent to the backend. But there will be no way to get trace based on trace_id in the V2 API :(

**Comment by chingor13** [comment]
The current plan is to remove the read endpoints from google-cloud-php trace library and change to use the V2 API only. Users can pin to an older, alpha version of the trace client library if they want to use the V1 API.

**Comment by chingor13** [comment]
Opened a PR with the Stackdriver Trace V2 client on the google-cloud-php repo: https://github.com/GoogleCloudPlatform/google-cloud-php/pull/763
