### ISSUE TITLE
Cannot set attributes on a detached span after the span is attached

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#78]
Note: the following also applies to adding annotations, links, message events, etc. to spans.

Consider:
```php
$span = Tracer::startSpan(['name' => 'root']);
$scope = Tracer::withSpan($span);
$span->addAttribute('foo', 'bar');
$scope->close();
```

This will work using the `ContextTracer` as the `$span` is a reference to the tracked span. This will not work for the extension as the `$span` is not a reference to the object being held in the extension's memory.

We could resolve this by delegating the addition of attributes to the `TracerInterface` implementation:
```php
interface TracerInterface
{
    ...
    // option 1
    public function addAttribute(Span $span, $key, $value);

    // option 2, $options['span'] would be the span, otherwise assume the current span.
    public function addAttribute($key, $value, $options = []);
}
```
The previous example would look like:
```php
$span = Tracer::startSpan(['name' => 'root']);
$scope = Tracer::withSpan($span);

// option 1
Tracer::addAttribute($span, 'foo', 'bar');

// option 2
Tracer::addAttribute('foo', 'bar', ['span' => $span]);

$scope->close();
```

Option 1 precludes you from being able to add attributes to the current span (common in the implicit span usage). Option 2 gets a bit hairy when applied to something like annotations or links where those models also have optional values.

**Comment by tmatsuo** [comment]
With the option 1, is it possible to keep the current span in the ExtensionTracer, make the `$span` optional, and then default to the current span?

Or how about to add some accessor functions in the extension?

**Comment by chingor13** [comment]
The point of option 2 would be to allow the span to be optional and default to the current span. In either case, the extension would need to add a way to add attributes to a span other than the current one.

The issue with having the extension returning a reference to it's internal span is that we'd be defining the same Span model in the extension and library (something like the protobuf extension and libraries do). These models are less stable than the protobuf ones.

**Comment by tmatsuo** [comment]
Anyway do you need to add a write accessors in the extension, receiving the span id and metadata?
Maybe you can add a read accessor that returns the current span id?

**Comment by tmatsuo** [comment]
I don't know why the option 2 is required. Why not
```php
Tracer::addAttribute('foo', 'bar'); // to the current span
// or
Tracer::addAttribute('foo', 'bar', $span);
```

**Comment by chingor13** [comment]
The extension would need to make the add attribute function accept the span id as an option to specify which span to add the attribute to. A read accessor already exists in that you can ask the extension for the current span context which contains the traceId and spanId.

**Comment by chingor13** [comment]
As for why option 2 has an options array, this whole issue also applies to annotations as well which has its own options (attributes).

```php
$span = Tracer::startSpan(['name' => 'root']);
$scope = Tracer::withSpan($span);

Tracer::addAnnotation('some message', [
    'span' => $span, 
    'attributes' => ['foo' => 'bar']
]);

$scope->close();
```

**Comment by tmatsuo** [comment]
Oh I see. Then maybe the option 2?
