### ISSUE TITLE
Segfault in extension when capturing arguments from watched functions.

### ISSUE THREAD

**Issue by chingor13** [census-instrumentation/opencensus-php#92]

**Comment by tmatsuo** [comment]
FYI, I also see segfault with a simpler case like

```php
Tracer::inSpan(['name' => 'slow function'], function() {
    sleep(2);
    echo 'Slept 2 seconds';
});

```

**Comment by chingor13** [comment]
I think the above example is a red herring. It appears this is an issue with sharing an internal HashTable as a user-space array and incorrectly bumping the gc count.
