### ISSUE TITLE
Conflict with snuffleupagus extension

### ISSUE THREAD

**Issue by remicollet** [census-instrumentation/opencensus-php#96]
FYI, I discover that both extensions are loaded, lot of strange issues appear

Pleae  see https://github.com/nbs-system/snuffleupagus/issues/133

**Comment by remicollet** [comment]
Fixed on snuffleupagus side, so was mostly FYI

**Comment by chingor13** [comment]
Thanks for the report! Yes, we hook `zend_execute_internal` to allow tracing of internal function calls. 

It looks like it's a variable naming conflict between the two extensions (both checking/using `orig_zend_execute_internal`). On the `opencensus` side, we should namespace our variable or fix the variable's visibility (or both if possible).
